config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'welcome/index'
  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:show, :edit, :update, :destroy]
	
	def index
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Hellz yeah, Mackenzie! Your article was successfully saved!"
		else
			render 'new', notice: "Oh no, Mackenzie! I was unable to save your post."
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Huzzah1  our article is updated successfully "
			else
				render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end




	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post
		@post = Post.friendly.find(params[:id])	
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rahil Ansari</title>
<link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header id="main_navigation" class="clearfix">
	<%= link_to "Rahil Ansari", root_path, class:"name" %> 
		<nav>
			<%= link_to "Articles", posts_path %>
			<a href="projects.html">Projects</a>
			<a href="contact.html">Contact</a>
		</nav>
</header><!-- /header -->

<%= yield %>


<footer id="main_footer">
<p class="copyright">&copy;2016 Rahil Ansari</p>
<nav>
	<a href="http://instagram.com/rahilansari261" target="_blank"><i class="fa fa-instagram"></i></a>
	<a href="http://medium.com/@rahilansari261" target="_blank"><i class="fa fa-medium"></i></a>
	<a href="http://github.com/ansarirahilJP" target="_blank"><i class="fa fa-github"></i></a>
	
</nav>
</footer>

</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
var disqus_shortname = 'bloggingsite';
var disqus_identifier = '<%= @post.id %>';
var disqus_title = '<%= @post.title %>';
var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//bloggingsite.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<h2><%= pluralize(@post.errors.count, "errors") %> prevented this post from saving:</h2>
<ul>
<% @post.errors.full_messagess.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>
<br>
<br>
<%= f.label :content, "Write your article here" %><br>
<%= f.text_field :content %>
<br>
<br>
<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Hello World</h1>


app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @post.created_at.strftime("%A, %b %d") %></p>
		<h1><%= @post.title %></h1>
		<hr>
	</header>
	<div id="content">
		<%= markdown @post.content %>
	</div><!-- /header -->
	<hr>

	<div id="share_box">
		<p> Share The Do List</p>
		<a href="#"><i class="fa fa-twitter"></i></a>
		<a href="#"><i class="fa fa-facebook"></i></a>
		<a href="#"><i class="fa fa-google-plus"></i></a>
	</div>

	<hr>
	<%= render 'disqus' %> 
</div>

<%= link_to "Edit", edit_post_path(@post) %>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
	<div class="col-1 about homepage_content">
		<h2>About</h2>
		<hr>
		<p>I'm a designer &amp; developer living in Jaipur RJ, India.
		</p>
		<p>By day I'm a Computer Science student in Poornima college Jaipur, by night I work as a front-end dev / designer at <a href="#">SkyTechno.</a>
		</p>
		<p>You can find me speaking in 140 characters on Twitter,writing some blogs on Medium, and sharing some code on Github.
		</p>
	</div>
	<div class="col-2 homepage_content">
		<h2>Stuff I've Written</h2>
		<hr>

		<% @posts.each do |post| %>
			<h3><a href="#"><%= link_to post.title, post %></a></h3>
			<p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
		<% end %>
		
	</div>
	<div class="col-3 homepage_content">
	<h2>Stuff I've Built</h2>
		<hr>
		<h3><a href="#">The Do list</a></h3>
		<p class="date">Friday April 10</p>
		<h3><a href="#">12 In 12 Challenge</a></h3>
		<p class="date">Friday April 10</p>
		<h3><a href="#">The Podcast</a></h3>
		<p class="date">Friday April 10</p>
	</div>
</div>